// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.igeekinc.indelible.indeliblefs.security;

public final class AuthenticatedServerImpl_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("java.rmi.Remote getServerInstanceForAuthenticationServer(com.igeekinc.indelible.oid.EntityID)"),
	new java.rmi.server.Operation("com.igeekinc.indelible.oid.EntityID listAuthenticationServers()[]")
    };
    
    private static final long interfaceHash = -3423690515186645370L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (hash != interfaceHash)
	    throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	
	com.igeekinc.indelible.indeliblefs.security.AuthenticatedServerImpl server = (com.igeekinc.indelible.indeliblefs.security.AuthenticatedServerImpl) obj;
	switch (opnum) {
	case 0: // getServerInstanceForAuthenticationServer(EntityID)
	{
	    com.igeekinc.indelible.oid.EntityID $param_EntityID_1;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_EntityID_1 = (com.igeekinc.indelible.oid.EntityID) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    java.rmi.Remote $result = server.getServerInstanceForAuthenticationServer($param_EntityID_1);
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 1: // listAuthenticationServers()
	{
	    call.releaseInputStream();
	    com.igeekinc.indelible.oid.EntityID[] $result = server.listAuthenticationServers();
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
