// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.igeekinc.indelible.indeliblefs.uniblock.server;

public final class RemoteCASSegmentIDIteratorImpl_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("void close()"),
	new java.rmi.server.Operation("boolean hasNext()"),
	new java.rmi.server.Operation("com.igeekinc.indelible.oid.CASSegmentID next()"),
	new java.rmi.server.Operation("void remove()")
    };
    
    private static final long interfaceHash = -5618111967574468873L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (hash != interfaceHash)
	    throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	
	com.igeekinc.indelible.indeliblefs.uniblock.server.RemoteCASSegmentIDIteratorImpl server = (com.igeekinc.indelible.indeliblefs.uniblock.server.RemoteCASSegmentIDIteratorImpl) obj;
	switch (opnum) {
	case 0: // close()
	{
	    call.releaseInputStream();
	    server.close();
	    try {
		call.getResultStream(true);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 1: // hasNext()
	{
	    call.releaseInputStream();
	    boolean $result = server.hasNext();
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeBoolean($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 2: // next()
	{
	    call.releaseInputStream();
	    com.igeekinc.indelible.oid.CASSegmentID $result = server.next();
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 3: // remove()
	{
	    call.releaseInputStream();
	    server.remove();
	    try {
		call.getResultStream(true);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
